/** Declaration file generated by dts-gen */


export declare interface ServiceCredentials {
  apikey: string;
  url: string;
  iam_apikey_name: string;
  iam_role_crn: string;
  iam_serviceid_crn: string;
}

export function  getCredentialsForService(serviceTag: string, serviceLabel: string, credentials: string): any;
export function  getDictionary(name: string): Record<string, string>;
export function  getString(name: string): string;
export function  init(mappingsFilePath: string): void;
export function  setLogLevel(level: any): void;
