/** Declaration file generated by dts-gen */
//export = tress;

export declare type TressJob = {
  name: string;
  payload?: any;
};

export declare type TressCallback = () => void;
export declare type TressDoneCallback = (err: any, response: any) => void;
export declare type TressWorkerCallback = (job: TressJob, done: TressDoneCallback) => void;

export declare type TressQueue = {
  push(jobs: TressJob[]):void;
  kill(): void;
  drain: TressCallback;
  empty: TressCallback;
  saturated: TressCallback;
  unsaturated: TressCallback;
  error: TressCallback;
  success: TressCallback;
};

export default function tress(workerCallback: TressWorkerCallback, concurrency: number): TressQueue;

